### ISSUE TITLE
0.13.4 release not available?

### ISSUE THREAD

**Issue by dleen** [almond-sh/almond#1056]
Hi @alexarchambault,

I'm trying to install the `0.13.4` [release](https://github.com/almond-sh/almond/releases/tag/v0.13.4) but I'm getting the following error:
```
./coursier bootstrap --standalone almond:0.13.4 --scala 2.12 -o almond212 -f
Picked up _JAVA_OPTIONS: -Duser.name=dleen
Exception in thread "main" coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for sh.almond:::scala-kernel:0.13.4 (likely a non existing module or version)
```

Am I doing something wrong or were all packages not published?

**Comment by alexarchambault** [comment]
The coursier CLI sometimes has issues inferring Scala versions (`almond` in the command above pulls [this app](https://github.com/coursier/apps/blob/main/apps/resources/almond.json), which brings `sh.almond:::scala-kernel:latest.release`, which needs a Scala version, and `--scala 2.12` doesn't bring an exact one).

I'd try either with a full Scala version, with `--scala 2.12.17` instead of `--scala 2.12`, or by forcing cache artifacts to be updated, with `-m force` (I suspect cache issues to be involved in that bug…)

**Comment by dleen** [comment]
Ah the specific scala version fixed it. This command worked:
```
./coursier bootstrap --standalone almond:0.13.4 --scala 2.12.17 -o almond212 -f
```
