### ISSUE TITLE
The `Future` returned from `Promise.complete` should be shown as `Success(...)` instead of `[running future]`

### ISSUE THREAD

**Issue by Atry** [almond-sh/almond#216]
<img width="1440" alt="2018-08-31 09 21 16" src="https://user-images.githubusercontent.com/601530/44887611-b0581280-acff-11e8-95be-42f9f5cf8704.png">

The unexpected output is:
```
res4: Promise[String] = [running future]
```

**Comment by alexarchambault** [comment]
Reproduced…

It should be an issue around the way ["updatable results"](https://github.com/jupyter-scala/jupyter-scala/blob/8aaa1d78e9ed65803383a6f2effb8fcd24b69866/modules/scala/scala-interpreter/src/main/scala/almond/internals/UpdatableResults.scala) are handled. Roughly, these work by pprinting UUIDs instead of stuff that can change, and later updating the corresponding `DisplayData`, each time replacing the UUID with something ("[running future]", "Success(…)", …)

**Comment by alexarchambault** [comment]
Possibly a concurrency issue 😓 (an update being sent before the data to be updated)
