### ISSUE TITLE
Improve handling of "rapid fire" completion requests

### ISSUE THREAD

**Issue by jameskoch** [almond-sh/almond#241]
The nteract front end is far more aggressive than Jupyter notebook about requesting completions from the kernel as the user types. There's some great UX that can be unlocked if this could work more seamlessly w/ Almond.

Ideally, when Almond receives a new completion request it would quickly interrupt an in-flight one to prioritize the new/latest one.

Would need to think about how this works in the "multiple front-ends attached to a single kernel" model (I don't know much about that world).

Discussed a bit in [this nteract issue](https://github.com/nteract/nteract/issues/3314).

**Comment by jameskoch** [comment]
From reading through [nsc.interactive tickets in the space of thread safety](https://issues.scala-lang.org/browse/SI-8239?jql=project%20%3D%20SI%20AND%20component%20%3D%20%22Presentation%20Compiler%22%20AND%20text%20~%20%22thread%22) it seems like you can ask PC to do things from multiple threads, though it sounds a bit like it might single-thread everything under the hood.

**Comment by rgbkrk** [comment]
> "multiple front-ends attached to a single kernel"

We made the architecture for this in Jupyter and while it's handy for debugging, it's not widely used (from a ZeroMQ standpoint). _However_, each client should have a unique session ID so it could be keyed on that.

**Comment by alexarchambault** [comment]
@jameskoch The scala presentation compiler, which handles completions, supports concurrent completion requests. Ammonite doesn't use that and [just blocks](https://github.com/lihaoyi/Ammonite/blob/28618679325bc1d90a72a2e0425b82a617a47d50/amm/interp/src/main/scala/ammonite/interp/Pressy.scala#L107) until a completion result arrives.

I guess the `ammonite.interp.Pressy` API can be tweaked, so that we can submit concurrent requests.

I'm going to tweak the `almond.interpreter.Interpreter` API so that it allows to run completions in a non-blocking and cancellable way.

**Comment by alexarchambault** [comment]
https://github.com/almond-sh/almond/pull/242 allows `Interpreter` implementations to handle completion requests asynchronously (by overriding `Interpreter.asyncComplete` rather than `Interpreter.complete`) and make them cancellable, and automatically cancels the currently running one when a new completion request arrives.

**Comment by alexarchambault** [comment]
@jameskoch I can look into having Ammonite accept concurrent completion requests, if you haven't already.

**Comment by jameskoch** [comment]
I haven't pushed ahead on this, and I wouldn't be nearly as effective as you in doing so. Have at it!

**Comment by alexarchambault** [comment]
https://github.com/lihaoyi/Ammonite/pull/893 should allow to handle more of the completion logic from almond, and make it interruptible in particular.
