### ISSUE TITLE
Syntax highlighting regression

### ISSUE THREAD

**Issue by david-bouyssie** [almond-sh/almond#398]
The syntax highlighting is not working anymore in the release ```0.6.0```.

![issue screenshot](https://files.gitter.im/almond-sh/almond/VJ9n/image.png)

After a short discussion with @sbrunk on gitter it seems to be a regression:
_the```language_info```field in the notebook metadata isn’t populated anymore_.

**Comment by sbrunk** [comment]
These JupyterLab issues for [R](https://github.com/jupyterlab/jupyterlab/issues/6760) and [Julia](https://github.com/jupyterlab/jupyterlab/issues/6826) look very similar.

The issue there is caused by the kernel not setting the `status` field in the [kernel_info_reply](https://jupyter-client.readthedocs.io/en/latest/messaging.html?highlight=kernel_info_reply#request-reply) as required by the spec and JupyterLab now checking this more strictly (not sure about Jupyter classic). I recall seeing error messages caused by the missing field in the browser console as well in JupyterLab 1.0.

Seems like we don't set the `status` field either yet so it *could* be the cause.

That strict checking has already been reverted in JupyteLab master for now (see https://github.com/jupyterlab/jupyterlab/pull/6860) but we should follow the spec nevertheless.
