### ISSUE TITLE
Classpath conflicts between multiple instances of ScalaInterpreters

### ISSUE THREAD

**Issue by supperslonic** [almond-sh/almond#452]
I have multiple instances of ScalaInterpreters in my custom kernel. I'm using SparkSession inside and for each interpeter i use the following startup code:
```
import org.apache.spark.sql._
val sparkSession = {NotebookSparkSession.builder()
.master("loca[1]").getOrCreate()}
```
I start my kernel with option `specificLoader=false` to share same instance of `sparkContext` and everything works fine, but from time to time (same code might work or throw an exception) I see serialization errors from spark and i believe it is related to classpath loader.
```
java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.spark.rdd.MapPartitionsRDD.f of type scala.Function3 in instance of org.apache.spark.rdd.MapPartitionsRDD
```
If I start my kernel with  `specificLoader=true` I don't see this error at all, but every interpreter creates a new instance of `sparkContext`, which I want to avoid.

My test code is the following:
```
val sc = sparkSession.sparkContext
val rdd = sc.parallelize(1 to 100, 10)
val n = rdd.map(_ + 1).sum()
```

**Comment by alexarchambault** [comment]
I'm not sure I understand what you're trying to achieve: you have a custom kernel, using `ScalaInterpreter`, and you're trying to have it act like multiple kernels at once, all sharing the same `SparkSession`, right?

If that's the case, one issue I see is that each instance of `ScalaInterpreter` [will set `spark.repl.class.uri`](https://github.com/alexarchambault/ammonite-spark/blob/f3f009e940fc19461279cda1cebc3b6302d06544/modules/core/src/main/scala/org/apache/spark/sql/ammonitesparkinternals/AmmoniteSparkSessionBuilder.scala#L272) in the spark conf. I'm not sure which one spark will retain at the end, but only one of them will likely be accessible. Parts of the logic of [ammonite-spark](https://github.com/alexarchambault/ammonite-spark) should be customized, so that only one such server is spawned for all the sessions.

Another problem you'll likely run into (I see you aluded to it on the Ammonite gitter) is that the `ScalaInterpreter`s will generate classes with similar names (like `cmd1`, `cmd2`, etc.), which is going to be a problem from the spark executors, which won't be able to distinguish between the classes of the various interpreters. That may require some customizations in Ammonite… (to put all classes of a session in a custom package for example).

**Comment by supperslonic** [comment]
> I'm not sure I understand what you're trying to achieve: you have a custom kernel, using `ScalaInterpreter`, and you're trying to have it act like multiple kernels at once, all sharing the same `SparkSession`, right?

Almost, same SparkContext. I have a custom kernel and it creates new ScalaInterpreter with it's own stream for each new Notebook SessionId.

I actually found where the issue is with this `ClassCastException`, but don't know how to solve it yet.
Looks like Spark is using the classLoader where the context has been created at first place for all serialization, but there is also a `closureSerializer` in Spark which is ALWAYS Javaserializer and it fails to deserialize data written from one classLoader to the current one of the interpreter.
And I can't set the correct classLoader in the serializer as I don't have any ref to it.

**Comment by supperslonic** [comment]
> That may require some customizations in Ammonite… (to put all classes of a session in a custom package for example).

How do you make a custom package in Ammonite ?

**Comment by alexarchambault** [comment]
> How do you make a custom package in Ammonite ?

I don't have a definite answer, but at the very end, the package is set in the compiled code [around here](https://github.com/lihaoyi/Ammonite/blob/649d2b3f603a6b250fc44cbbe9d5d6a37afbde9f/amm/interp/src/main/scala/ammonite/interp/CodeWrapper.scala#L29-L30). By navigating your way in the Ammonite code from there, it may be possible to pass a custom package prefix to `ammonite.interp.Interpreter` so that it ends up being used there.

Alternatively, the `cmd` prefix in the class name is defined [here](https://github.com/lihaoyi/Ammonite/blob/71e4df44e709805f976587306d50e2f874e24272/amm/interp/src/main/scala/ammonite/interp/Interpreter.scala#L233). Just allowing to customize it via a field passed to `ammonite.interp.Interpreter` (and set it yourself to `"cmd1_"`, `"cmd2_"`, etc. so that the classes are named `"cmd1_1"`, `"cmd1_2"`, …) may work as well, and would probably be more straightforward.

The Ammonite README has some [doc detailing manual commands](https://github.com/lihaoyi/Ammonite/#common-commands) to quickly test that kind of changes.

**Comment by supperslonic** [comment]
Thank you for your help. I will close an issue!

**Comment by navado** [comment]
Sorry for bringing this up
@supperslonic What was your solution for the Spark issue?

**Comment by supperslonic** [comment]
Hey, @navado !
We had to modify some internal classes like the HTTP endpoint responsible for handling REPL and `CodeClassWrapper`.
Each Interpreter is using its own package and its own classloader.
REPL service endpoint detects by the package name which classloader to use to get the lambda-generated classes.
